# === application.yml ===

spring:
  datasource:
    url: jdbc:postgresql://localhost:5441/csvimport
    username: csvadmin
    password: csvpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  flyway:
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG
